package visao;
import java.awt.Image;
import java.awt.Graphics;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JFrame;


public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        //ImageIcon icon = new ImageIcon(getClass().getResource("/imagem/fundo.png"));
        //final Image image = icon.getImage();
        jAreaTrabalho = new javax.swing.JDesktopPane(){

            public void paintComponent(Graphics g){
                g.drawImage(null,800,600,getWidth(), getHeight(),this);

            };

        };
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmCadastro = new javax.swing.JMenu();
        jmiCadProduto = new javax.swing.JMenuItem();
        jmConsulta = new javax.swing.JMenu();
        jmiComJtable = new javax.swing.JMenuItem();
        jmSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Fundo.png"))); // NOI18N
        jAreaTrabalho.add(jLabel1);
        jLabel1.setBounds(0, 0, 1920, 1080);

        jMenuBar1.setBackground(new java.awt.Color(51, 153, 255));
        jMenuBar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuBar1.setAlignmentY(1.0F);
        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jmCadastro.setText("Cadastro");

        jmiCadProduto.setText("Paciente");
        jmiCadProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCadProdutoActionPerformed(evt);
            }
        });
        jmCadastro.add(jmiCadProduto);

        jMenuBar1.add(jmCadastro);

        jmConsulta.setText("Busca");

        jmiComJtable.setText("Paciente");
        jmiComJtable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiComJtableActionPerformed(evt);
            }
        });
        jmConsulta.add(jmiComJtable);

        jMenuBar1.add(jmConsulta);

        jmSair.setText("Sair");
        jmSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmSairMouseClicked(evt);
            }
        });
        jMenuBar1.add(jmSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jAreaTrabalho, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jAreaTrabalho, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private GuiCadPaciente gcp; // Declaração fora dos métodos para que seja acessível a todos
private GuiJTableBuscaPaciente gmp; // Corrigido para GuiJTableBuscaPaciente

private void abrirCadPaciente() {
    gcp = new GuiCadPaciente();
    jAreaTrabalho.add(gcp);
    gcp.setVisible(true);
}

private void abrirJanelaTable() {
    gmp = new GuiJTableBuscaPaciente(); // Corrigido para GuiJTableBuscaPaciente
    jAreaTrabalho.add(gmp);
    gmp.setVisible(true);
}

private void fecharCadPaciente() {
    if (gcp != null) {
        gcp.setVisible(false);
    }
}

private void fecharJanelaTable() {
    if (gmp != null) {
        gmp.setVisible(false);
    }
}
    private void jmiCadProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCadProdutoActionPerformed
        abrirCadPaciente();
        fecharJanelaTable();
    }//GEN-LAST:event_jmiCadProdutoActionPerformed

    private void jmiComJtableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiComJtableActionPerformed
        abrirJanelaTable();
        fecharCadPaciente();
    }//GEN-LAST:event_jmiComJtableActionPerformed

    private void jmSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmSairMouseClicked
        System.exit(EXIT_ON_CLOSE);
    }//GEN-LAST:event_jmSairMouseClicked
public static void main(String args[]) {
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }

    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            Menu mainApp = new Menu(); // Aqui está a correção
            mainApp.setDefaultCloseOperation(Menu.EXIT_ON_CLOSE);
            mainApp.setResizable(false); // Impede redimensionamento da janela
            mainApp.setVisible(true);
        }
    });
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jAreaTrabalho;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jmCadastro;
    private javax.swing.JMenu jmConsulta;
    private javax.swing.JMenu jmSair;
    private javax.swing.JMenuItem jmiCadProduto;
    private javax.swing.JMenuItem jmiComJtable;
    // End of variables declaration//GEN-END:variables
}
